# Assignment Questions_List

In [90]:
input_data =input("comma-separated")
input_list = input_data.split(",")
input_tuple = tuple(input_list)
print("List : ", input_list)
print("Tuple : ", input_tuple)

comma-separated3,5,7,23
List :  ['3', '5', '7', '23']
Tuple :  ('3', '5', '7', '23')


In [91]:
color_list = ["Red","Green","White" ,"Black"]
first_colour =color_list[0]
last_colour =color_list[-1]
print("first_colour = ",first_colour)
print("last_colour = ",last_colour)

first_colour =  Red
last_colour =  Black


In [103]:
Sample_List = [1, 2, 3, 4, 5, 6, 7, 8, 9]
Even_num = [x for x in Sample_List if x % 2 == 0]
print("Even numbers:", Even_num)

Even numbers: [2, 4, 6, 8]


# Module

In [3]:
from datetime import date 
date1 = date(2014, 7, 2)
date2 = date(2014, 7, 11)
diff= date2 - date1
print('diff = ',diff.days,'days')

diff =  9 days


# Functions

In [108]:
import math
R=6
volume_sphere = (4/3)*(math.pi)*(R)*(R)*(R)
print("Volum_sphere = ",volume_sphere)

Volum_sphere =  904.7786842338604


In [115]:
def sum_of_three_no(x1,x2,x3):
    if x1==x2==x3:
        return 3*(x1+x2+x3)
    else:
        return x1+x2+x3
print(sum_of_three_no(2,2,2))
print(sum_of_three_no(3,2,1))

18
6


In [117]:
List = [1,4,6,8,4,9,4]
count = List.count(4)
print(count)

3


In [132]:
def even_no(lst):
    for x in lst:
        if x == 237:
            break
        elif x % 2 == 0:
            print(x)
my_lst = [399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217, 815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717, 958, 743, 527]
print_even_until_237(my_lst)

162
758
918


In [133]:
for x in range(1500 , 2701):
    if x % 7 == 0 and x % 5 == 0 :
        print(x)

1505
1540
1575
1610
1645
1680
1715
1750
1785
1820
1855
1890
1925
1960
1995
2030
2065
2100
2135
2170
2205
2240
2275
2310
2345
2380
2415
2450
2485
2520
2555
2590
2625
2660
2695


In [140]:
for x in range(7):
    if x == 3 or x == 6:
        continue 
    print(x ,end=' ')

0 1 2 4 5 

In [144]:
a , b = 0, 1
while b<50:
    print(b,end=' ')
    a,b=b,a+b    

1 1 2 3 5 8 13 21 34 

In [147]:
Sample_List = [1,2,3,3,3,3,4,5]
my_set = set(Sample_List)
unique_list = list(my_set)
print(unique_list)

[1, 2, 3, 4, 5]


# Strings

In [158]:
sample = ['chatrapati','shivaji','maharaj','ki','jay']
concatenate = ' '
for x in sample:
    concatenate = concatenate +' '+ x
print(concatenate)

  chatrapati shivaji maharaj ki jay


# Dictionary

In [105]:
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
Expected_Result = dic1|dic2|dic3
print(Expected_Result)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


#  Series

In [157]:
import pandas as pd
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

#add
add = s1+s2
print(add)

#subtract
sub = s1-s2
print(sub)

#multiple
mult = s1*s2
print(mult)

#divide 
div = s1/s2
print(div)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# Data Frame

In [10]:
import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
select_df = df.loc[['b','d','f','g'], ['name','score']]
print(select_df)

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5


In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
cr = pd.read_csv('crime_data.csv')

print(cr.value_counts())

#histogram
plt.hist(cr["     "], 
         bins = 50,
        )

sns.distplot(cr["    "], 
             bins=10
#boxplot
plt.boxplot(x='    ',
            data=cr,
           )
             
sns.boxplot(x="     ",
           data=cr)
#scatterplot
plt.scatter(cr['    '],
            cr['     '], alpha = 0.5
           )
             
sns.scatterplot(x='    ', 
                y='cr', 
                data=tips_df
               )

#barplot
plt.bar(x = cr["     "], 
        height = cr["    "]
       )
sns.barplot(x='   ',
            y='    ',
            data=cr, 
            palette='viridis'
           )

#piechart
plt.pie(cr)


Unnamed: 0      Murder  Assault  UrbanPop  Rape
Alabama         13.2    236      58        21.2    1
Pennsylvania    6.3     106      72        14.9    1
Nevada          12.2    252      81        46.0    1
New Hampshire   2.1     57       56        9.5     1
New Jersey      7.4     159      89        18.8    1
New Mexico      11.4    285      70        32.1    1
New York        11.1    254      86        26.1    1
North Carolina  13.0    337      45        16.1    1
North Dakota    0.8     45       44        7.3     1
Ohio            7.3     120      75        21.4    1
Oklahoma        6.6     151      68        20.0    1
Oregon          4.9     159      67        29.3    1
Rhode Island    3.4     174      87        8.3     1
Alaska          10.0    263      48        44.5    1
South Carolina  14.4    279      48        22.5    1
South Dakota    3.8     86       45        12.8    1
Tennessee       13.2    188      59        26.9    1
Texas           12.7    201      80        25.5    

In [79]:
import pandas as pd
import numpy as np
mtcars = pd.read_csv('mtcars.csv')

mtcars.drop([10,11,12,13,14,15],axis=0)

mtcars.drop(vol ,axis=1)



mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [81]:
import pandas as pd
import numpy as np
bank_full = pd.read_csv('bank-full.csv')

bank_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 1 columns):
 #   Column                                                                                                                                                Non-Null Count  Dtype 
---  ------                                                                                                                                                --------------  ----- 
 0   age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"  45211 non-null  object
dtypes: object(1)
memory usage: 353.3+ KB


# Basic Programs

In [82]:
a = 10
b = 5
print("Addition: ", a + b)
print("Subtraction: ", a - b)
print("Multiplication: ", a * b)
print("Division: ", a / b)
print("Modulus: ", a % b)
print("Exponentiation: ", a ** b)  
print("Floor Division: ", a // b)  

Addition:  15
Subtraction:  5
Multiplication:  50
Division:  2.0
Modulus:  0
Exponentiation:  100000
Floor Division:  2


In [83]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# slice the list to get the first five elements
first_five = numbers[:5]
print(first_five)
# slice the list to get the last five elements
last_five = numbers[-5:]
print(last_five)
# slice the list to get every other element
every_other = numbers[::2]
print(every_other)
# slice the list to get the elements in reverse order
reverse = numbers[::-1]
print(reverse)

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [85]:
total = 0
while total<100:
    num = int(input("Enter a number"))
    total+=num
print('sum',total)

Enter a number1
Enter a number2
Enter a number3
Enter a number4
Enter a number5
Enter a number6
Enter a number7
Enter a number8
Enter a number9
Enter a number10
Enter a number11
Enter a number12
Enter a number13
Enter a number14
sum 105


In [86]:
import numpy as np
mat =  np.arange(2, 11)
matrix= mat.reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [87]:
import numpy as np
value_list =[1,2,3,4,5]
array_nyp = np.array(value_list)
print("list_of_value:",value_list)
print("numpy_of_array:",array_nyp)

list_of_value: [1, 2, 3, 4, 5]
numpy_of_array: [1 2 3 4 5]


In [93]:
import numpy as np
null_vector = np.zeros(10)
null_vector[5]=11
print(null_vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]
